# $NetBSD$

DISTNAME=	libserialport-0.1.2
CATEGORIES=	cad
MASTER_SITES=	https://sigrok.org/download/source/libserialport/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://sigrok.org/wiki/Libserialport
COMMENT=	Cross-platform shared library for accessing serial ports
LICENSE=	gnu-lgpl-v3

GNU_CONFIGURE=		yes
USE_LIBTOOL=		yes
USE_TOOLS+=		pkg-config
USE_LANGUAGES=		c

.include "../../mk/bsd.pkg.mk"
